---
id: heroku-meetup-13
base_name: groonga-on-heroku
tags:
- rabbit
- heroku
- groonga
- full-text-search
presentation_date: 2015-01-13
version: 2015.1.13.1
licenses:
- CC BY-SA 4.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
